import type { NextPage } from 'next';
import Head from 'next/head';
import { Fragment } from 'react';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
    
    return (
        <Fragment>

            <Head>
                <title>Alvin Quach - Personal Portfolio</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/images/favicon.ico' />
            </Head>
            <div className={styles.container}>

                <main className={styles.main}>
                    <h1 className={styles.title}>
                        This page is under construction
                    </h1>

                    <p className={styles.description}>
                        Meanwhile, you check out the links below
                    </p>

                    <div className={styles.grid}>
                        <a 
                            className={styles.card}
                            href='https://github.com/alvinquach'
                            target='_blank'
                            rel='noopener noreferrer'
                        >
                            <h2>GitHub &rarr;</h2>
                            <p>Check out my GitHub repositories!</p>
                        </a>
                        <a 
                            className={styles.card}
                            href='https://linkedin.com/in/alvinquach/'
                            target='_blank'
                            rel='noopener noreferrer'
                        >
                            <h2>LinkedIn &rarr;</h2>
                            <p>View my LinkedIn profile.</p>
                        </a>
                    </div>
                </main>
            </div>
        </Fragment>
    );

};

export default Home;
